name: Build and cross-compile

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-firmware:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: armv7-unknown-linux-gnueabihf

      - name: Install Cross
        run: |
          curl -L--proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall cross --no-confirm

      - name: Build for armv7-unknown-linux-gnueabihf
        run: cross build --release --target armv7-unknown-linux-gnueabihf
