name: Build and cross-compile

on:
  push:
    branches: [ "main", "master" ]
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  build-firmware:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      - name: Install Toolchain
        run: |
          apt update
          apt install -y build-essential curl zip unzip
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"
          cargo install cross

      - name: Build for armv7-unknown-linux-gnueabihf
        run: |
          . "$HOME/.cargo/env"
          cross build --release --target armv7-unknown-linux-gnueabihf

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: uvc_rtsp_forwarder-armv7
          path: target/armv7-unknown-linux-gnueabihf/release/uvc_rtsp_forwarder 

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: target/armv7-unknown-linux-gnueabihf/release/uvc_rtsp_forwarder
          generate_release_notes: true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}